version: '3'
services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    #image: node:lts-jessie
    ports:
      - "3100:3000"
    environment:
      NUXEO_URL: "http://nuxeo.yourcorp.com:8080/nuxeo"
      NUXEO_LOGIN: Administrator
      NUXEO_PASSWORD: Administrator
      NUXEO_PUBLIC_URL: "http://nuxeo.yourcorp.com/nuxeo"
    volumes:
      - ".data_local:/usr/app/data"
      - ".data_global:/usr/local/lib/node_modules/nuxeo-node-example/data"
